plugins { id 'com.android.application' }
android {
    namespace 'org.ylports.aseprite'
    compileSdk 35
    ndkVersion '27.2.12479018'
    defaultConfig {
        applicationId 'org.ylports.aseprite.experimental'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0-core-alpha'
        ndk { abiFilters 'arm64-v8a' }
        externalNativeBuild { cmake { arguments '-DANDROID_STL=c++_static', '-DCMAKE_POLICY_VERSION_MINIMUM=3.5'; cppFlags '-std=c++17 -fexceptions -frtti' } }
    }
    buildTypes { debug { debuggable true }; release { minifyEnabled false } }
    externalNativeBuild { cmake { path file('src/main/cpp/CMakeLists.txt'); version '3.22.1' } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
